/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Rollup Builder schema for Architect.
 */
export interface RollupBuilderSchema {
  /**
   * The path to the Rollup configuration file.
   */
  rollupConfig: string;
  tsConfig: string;
  /**
   * Run build when files change.
   */
  watch?: boolean;
}
